### ISSUE TITLE
Fejler ved søgning

### ISSUE THREAD

**Issue by baffioso** [danielarnason/Python#1]
Ved søgningen: islands brygge 33, kbh s
Kommer følgende fejl: 
```
Traceback (most recent call last):
  File "adressevasker.py", line 20, in <module>
    adr_url = js_data['resultater'][0]['aktueladresse']['href']
KeyError: 'href'
```

**Comment by danielarnason** [comment]
Det ser ud til, at der ikke er en 'href' attribut i det JSON objekt som datavaskeren returnerer. 
[http://dawa.aws.dk/datavask/adresser?betegnelse=islands+brygge+33%2C+kbh+s](url)
plus det, at den faktisk ikke finder nr 33, men nr 93. Hvorfor nr 93 ikke har en 'href', aner jeg ikke. Jeg troede, at alle eksisterende adresser havde en.

Hvis den returnerer Kategori C, så er det som regel en forkert adresse, den har fundet frem.
