### ISSUE TITLE
Iterer gennem rækker i CSV-fil og tilføj kolonner med bl.a. koordinater

### ISSUE THREAD

**Issue by baffioso** [danielarnason/Python#2]
Kan være der skal hentes inspiration fra MMQGIS-pluginnet:
https://github.com/GeoICON/edugis-mmqgis/blob/master/mmqgis_library.py (dette er vist en fork)

**Comment by danielarnason** [comment]
Jeg har droppet Python 2 for dette. Csv modulet i Python 3 er vist meget bedre til at håndtere danske bogstaver og den slags.

**Comment by danielarnason** [comment]
Done!
