### ISSUE TITLE
Lad ogr2ogr konvertere zippede filer til PostGIS

### ISSUE THREAD

**Issue by baffioso** [danielarnason/Python#3]
Det kan overvejes om det er nødvendigt at [hente .shp filer fra FTP](https://github.com/danielarnason/Python/blob/master/scripts/atom_feeds_gst#L33-L56) og [unzippe](https://github.com/danielarnason/Python/blob/master/scripts/atom_feeds_gst#L75-L86), da ogr2ogr direkte kan konvertere de zippede .shp på FTP til PostGIS.

**Comment by danielarnason** [comment]
Zip filen, der bliver hentet indeholder masser af foldere, men ikke kun shapefilerne. Jeg ved ikke om det kan give problemer.
